### ISSUE TITLE
Mu0 transposed?

### ISSUE THREAD

**Issue by ccraddock** [asoroosh/DVARS#2]
https://github.com/asoroosh/DVARS/blob/50f65d9f7570dffffd4204f0304f571b030c82fb/DVARSCalc.m#L374

Shouldn't this line be:

```Stat.Mu0        = mean(IQRsd(Y'));```

To make it more consistent with the other uses of IQRsd? Or is Mu0 meant to be the mean of volume sds rather than the mean of voxel sds?

**Comment by asoroosh** [comment]
Mu0 is a variable we used to evaluate the simulations -- see Fig. 2 of the [manuscript](https://www.sciencedirect.com/science/article/pii/S1053811917311229?via%3Dihub#fig2). I should have removed the this variable after the simulations are done. BUT, do you think there would be any merit to the mean of voxel sds? Does it tell us anything more than what A-var component explains?
