### ISSUE TITLE
Recasting data type as double

### ISSUE THREAD

**Issue by parekhpravesh** [asoroosh/DVARS#4]
Hi,

When running fMRIDiag_plot, an error pops up if the data type is int16 (when demeaning the data; line 386); it would be best if the input data is recast as double type so that all processing becomes compatible. The error does not happen if the NIfTI files are read using SPM (but load_untouch_nii may return data in int16 type).

**Comment by asoroosh** [comment]
Added line below:
https://github.com/asoroosh/DVARS/blob/7379297ac1d710847ef49e276c0595b4be76cb55/fMRIDiag_plot.m#L358

Thanks for your comment.
