### ISSUE TITLE
Use of "contains" in DSEvars (compatibility with older MATLAB versions)

### ISSUE THREAD

**Issue by parekhpravesh** [asoroosh/DVARS#5]
Hi,

Lines 170 and 176 in the DSEvars.m file uses the MATLAB function "contains" which was introduced in R2016b. This would thrown up an error when using older versions of MATLAB. This could be replaced with strcmpi probably.

**Comment by asoroosh** [comment]
I initially tried `strcmpi`, although it doesn't do what `contains` does. See example below:
```
>> a = 'Foo.dtseries'

>> strcmpi(a,'.dtseries')

ans =

   0
>> contains(a,'.dtseries')

ans =

   1
```

I suspect a fundamental solution to this would be `regexp`?

**Comment by parekhpravesh** [comment]
Hello,
Thanks for taking a look. Yes indeed, it would be better to switch to `regexp `. The other alternate is to use `strfind(a,'.dtseries')` which would (like `regexp`) return the position where it happens to find the substring (otherwise returning an empty variable like `regexp`). Both these cases should work fine with the `if else` condition at those lines (the empty variable will work as a substitute for 0 while any positive value would be interpreted as 1 for the condition check).

**Comment by asoroosh** [comment]
I added a comment before `contains` functions which explains how to get the code up and running in case of MATLAB <2016 versions. I belive `strfind` may not be as robust as contain in cases  where users mistakenly input the wrong file name. 

https://github.com/asoroosh/DVARS/blob/b7910af4f10800b16291eb8c6dc6bb0fc90f9e3a/DSEvars.m#L178

Thank you so much for time and your comments.

-Soroosh
